site_name: Babushka ML


# Project information
site_author: Daisuke Kuwabara
# Repository
repo_name: kwdaisuke/kwdaisuke.github.io
repo_url: https://github.com/kwdaisuke/kwdaisuke.github.io
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2016 - 2022 Daisuke Kuwabara

# Configuration
theme:
  name: material
  palette:
    primary: brown
  features:
    - navigation.tabs
    - toc.integrate
    - header.autohide
  logo: "assets/babushka_black.png"




# Customization
extra:
  analytics:
    provider: google
    property: G-180F37E220
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!

  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCERuVu6ZkMC3_E7d0crNS2A
    - icon: fontawesome/brands/github
      link: https://github.com/kwdaisuke
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/daisuke-kuwabara-5b821519b/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/babushka_ml
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/emi_ndk

plugins:
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          build: true
        jp:
          name: Japanese
          build: true
        fr:
          name: Français
          build: true
  - mkdocs-jupyter


# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


# Page tree
nav:
  - Daisuke Kuwabara: daisuke.md
  - Blog: 
     LLM: blog/rlhf.md
  - Biblio:
      MLOps: MLOps/mlops.md
      Python:
        Introduction: MLOps/Python/introduction.md
        Async: MLOps/Python/async.py
      Software Engineering:
        API: MLOps/SoftwareEngineering/api.md
        Object Oriented Programming: MLOps/SoftwareEngineering/oop.md
        SOLID: MLOps/SoftwareEngineering/solid.md
        Networking: MLOps/SoftwareEngineering/network.md
        Microservice: MLOps/SoftwareEngineering/microservice.md
      Data Structure: MLOps/DataStructure/ds.md
      Mathematics:
        KL Divergence: MLOps/Mathematics/KL_divergence.md
      Machine Learning:
        Introduction: MLOps/MachineLearning/intro.md
      Data Engineering:
        SQL: MLOps/DataEngineering/SQL.md
  - Why Babushka?: babushka.md
# Set language for search

extra_files:
  - CNAME