site_name: Babushka ML
docs_dir: '../../docs/jp'
site_dir: '../../generated/jp'




# Project information

site_author: Daisuke Kuwabara
# Repository
repo_name: kwdaisuke/kwdaisuke.github.io
repo_url: https://github.com/kwdaisuke/kwdaisuke.github.io
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2016 - 2022 Daisuke Kuwabara

# Configuration
theme:
  name: material
  language: en
  palette:
    prim ary: brown
    scheme: slate
  features:
    - navigation.tabs
    - toc.integrate
    - header.autohide



# Customization
extra:
  analytics: 
    provider: google
    property: G-180F37E220
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!

  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCERuVu6ZkMC3_E7d0crNS2A
    - icon: fontawesome/brands/github
      link: https://github.com/kwdaisuke
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/daisuke-kuwabara-5b821519b/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/babushka_ml
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/emi_ndk
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 日本語
      link: /jp/
      lang: jp
    - name: Français
      link: /fr/
      lang: fr
# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


# Page tree
nav:
  - メッセージ: index.md
  - Course: course.md
  - Blog:
    - Why Babushka?: blog/babushka.md
    - Data Engineer: blog/data_engineer.md
    - Airflow: blog/airflow.md
    - Using Tensorflow Transform in Apache Beam: blog/tft_beam.md
  - Break Room:
    - Find your ideal place: breakroom/break.md
    - Living in Japan: breakroom/japan.md
    - Living in Turkey: breakroom/turkey.md
    - Living in France: breakroom/france.md
  - About Daisuke Kuwabara: daisuke.md

plugins:
  - search:
      lang: jp                                      # Set language for search
